---
- hosts: dockerhost
  become: true
  vars:
    pip_package: python-pip
    pip_executable: "{{ 'pip3' if pip_package.startswith('python3') else 'pip' }}"
    pip_install_packages: ["docker-py"]
    
    
  roles:
  - role: docker
  - role: pip_install_packages
      
- hosts: app
  become: true
  tasks:
  
  - pause:  minutes=3
  
  - name: Check if Swarm has already been Initialized
    shell: docker node ls
    register: swarm_status
    ignore_errors: true
 
  - name: Initialize Docker Swarm
    shell: >
        docker swarm init
        --advertise-addr={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:2377
    when: swarm_status.rc != 0
    run_once: true
    

  - name: Get the Manager join-token
    shell: docker swarm join-token --quiet manager
    register: manager_token

  - name: Get infos on network
    docker_network_info:
      name: imnet
    register: result 
       
  - name: Add overlay network imnet
    shell: docker network create -d overlay --attachable imnet
    when: result.exists == False
  

- hosts: db
  become: true
  tasks:
  - name: Check if Swarm is Already Initialized
    shell: docker node ls
    register: swarm_status
    ignore_errors: true
    

  - name: Add Managers to the Swarm
    shell: "docker swarm join --token {{ hostvars['apps']['manager_token']['stdout'] }} {{ hostvars['apps']['ansible_default_ipv4']['address'] }}:2377"
    when: swarm_status.rc != 0
     



